core/urls.py
from django.urls import path
from .views import dashboard, home_page

app_name = 'core'

urlpatterns = [
    path('', home_page, name='home'),
    path('dashboard/', dashboard, name='dashboard')
]

customers/urls.py
from django.urls import path
from .views import customer_detail, customer_list, customer_create, customer_update, customer_delete


app_name = 'customers'

urlpatterns = [
    path('', customer_list, name='customer-list'),
    path('<int:pk>/', customer_detail, name='customer-detail'),
    path('create/', customer_create, name='customer-create'),
    path('update/<int:pk>', customer_update, name='customer-update'),
    path('delete/<int:pk>', customer_delete, name='customer-delete'),
]

main/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('products/', include('products.urls', namespace='products')),
    path('customers/', include('customers.urls', namespace='customers')),
    path('brands/', include('brands.urls', namespace='brands')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('authentication/', include('accounts.urls', namespace='accounts')),
]


# Adding STATIC and MEDIA
urlpatterns += static(settings.STATIC_URL,
                      document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL,
                      document_root=settings.MEDIA_ROOT)


admin.site.site_header = "shisaStore"

orders/urls.py
from django.urls import path
from .views import order_create, order_create_customer, order_detail, order_list, order_update, order_delete, order_create_customer

app_name = 'orders'

urlpatterns = [
    path('', order_list, name='order-list'),
    path('<int:pk>/', order_detail, name='order-detail'),

    path('create/', order_create, name='order-create'),
    path('create/<int:pk>', order_create_customer, name='order-create-customer'),
    path('update/<int:pk>', order_update, name='order-update'),
    path('delete/<int:pk>', order_delete, name='order-delete'),

]

core/models.py
from django.db import models

# Create your models here.

core/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render
from orders.models import Order
from customers.models import Customer
from products.models import Product
from accounts.decorators import allowed_users


def home_page(request):

    products = Product.objects.all()

    return render(request, 'core/home_page.html', {

        'products': products,

    })


@login_required(login_url='accounts:login')
@allowed_users(allowed_roles=['admin'])
def dashboard(request):

    orders = Order.objects.all().order_by('-created')
    customers = Customer.objects.all()
    total_customers = customers.count()
    total_orders = orders.count()
    delivered = orders.filter(status='DELIVERED').count()
    pending = orders.filter(status='PENDING').count()

    return render(request, 'core/dashboard.html', {
        'orders': orders,
        'customers': customers,
        'total_customers': total_customers,
        'total_orders': total_orders,
        'delivered': delivered,
        'pending': pending,

    })

core/templates/core/dashboard.html
{% extends 'base.html' %}
{% block title %}Dashboard{% endblock title %}
{% block content %}
{% include 'status.html' %}
<div class="row mt-5">
    <div class="col-md-5">
        <h5>Customers:</h5>
        <hr>
        <div class="card card-body shadow">
            <a class="btn btn-info btn-sm btn-block" href="{% url 'customers:customer-create' %}">Create Customer</a>
            <table class="table table-hover text-center align-middle">
                <tr>
                    <th>Customer</th>
                    <th>Phone</th>
                </tr>
                {% for customer in customers %}
                <tr>
                    <th><a class="my-main-text" href="{{ customer.get_absolute_url }}">{{ customer.full_name }}</a></th>
                    <th class="my-main-text">{{ customer.phone }}</th>
                </tr>
                {% endfor %}
            </table>
        </div>
    </div>
    <div class="col-md-7">
        <h5>Last 5 Orders:</h5>
        <hr>
        <div class="card card-body text-center shadow">
            <!-- <a class="btn btn-info btn-sm btn-block" href="{% url 'orders:order-create' %}">Create Order</a> -->
            <table class="table table-hover text-center align-middle">
                <thead>
                    <tr>
                        <th scope="col">Product</th>
                        <th scope="col">Customer</th>
                        <th scope="col">Status</th>
                        <th scope="col">Update</th>
                        <th scope="col">Remove</th>
                    </tr>
                </thead>
                {% for order in orders %}
                <tbody>
                    <tr>
                        <th><a class="my-main-text" href="{{ order.get_absolute_url }}">{{ order.product.name }}</a>
                        </th>
                        <th class="my-main-text">{{ order.customer.full_name}}</th>
                        {% if order.status == 'PENDING'%}
                        <th><span class="mystatus-pending"><strong>{{ order.status }}</strong></span></th>
                        {% elif order.status == 'READY' %}
                        <th><span class="mystatus-ready"><strong>{{ order.status }}</strong></span></th>
                        {% elif order.status == 'DELIVERED' %}
                        <th><span class="mystatus-delivered"><strong>{{ order.status }}</strong></span></th>
                        {% endif %}
                        <th><a class="btn btn-sm btn-info w-100"
                                href="{% url 'orders:order-update' order.pk %}">Update</a></th>
                        <th><a class="btn btn-sm btn-danger w-100"
                                href="{% url 'orders:order-delete' order.pk %}">Remove</a></th>
                    </tr>
                </tbody>
                {% endfor %}
            </table>
        </div>
    </div>
</div>

{% endblock content %}

core/templates/core/home_page.html
{% extends 'base.html' %}
{% block title %}Home{% endblock title %}
{% block content %}
<div class="container mt-5">
    <div class="row row-cols-1 row-cols-md-3 g-4">
        {% for product in products %}
        <div class="col">
            <div class="card shadow p-3 mb-5 rounded">
                <div class="card-body">
                    <h5 class="card-title text-center"><strong>{{ product.name }}</strong></h5>
                    <hr>
                    <p class="card-text text-primary display-6 text-center">{{ product.price }}</p>
                    <hr>
                    <p class="card-text text-center"><strong>{{ product.brand.name }}</strong></p>
                    <a href="#" class="btn btn-primary">Add to Cart</a>
                    <a href="#" class="btn btn-info">Details</a>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock content %}