core/urls.py
from django.urls import path
from .views import dashboard, home_page

app_name = 'core'

urlpatterns = [
    path('', home_page, name='home'),
    path('dashboard/', dashboard, name='dashboard')
]

customers/urls.py
from django.urls import path
from .views import customer_detail, customer_list, customer_create, customer_update, customer_delete


app_name = 'customers'

urlpatterns = [
    path('', customer_list, name='customer-list'),
    path('<int:pk>/', customer_detail, name='customer-detail'),
    path('create/', customer_create, name='customer-create'),
    path('update/<int:pk>', customer_update, name='customer-update'),
    path('delete/<int:pk>', customer_delete, name='customer-delete'),
]

main/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('products/', include('products.urls', namespace='products')),
    path('customers/', include('customers.urls', namespace='customers')),
    path('brands/', include('brands.urls', namespace='brands')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('authentication/', include('accounts.urls', namespace='accounts')),
]


# Adding STATIC and MEDIA
urlpatterns += static(settings.STATIC_URL,
                      document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL,
                      document_root=settings.MEDIA_ROOT)


admin.site.site_header = "shisaStore"

orders/urls.py
from django.urls import path
from .views import order_create, order_create_customer, order_detail, order_list, order_update, order_delete, order_create_customer

app_name = 'orders'

urlpatterns = [
    path('', order_list, name='order-list'),
    path('<int:pk>/', order_detail, name='order-detail'),

    path('create/', order_create, name='order-create'),
    path('create/<int:pk>', order_create_customer, name='order-create-customer'),
    path('update/<int:pk>', order_update, name='order-update'),
    path('delete/<int:pk>', order_delete, name='order-delete'),

]

customers/models.py
from django.db import models
from django.urls import reverse


class Customer(models.Model):

    full_name = models.CharField(max_length=120)
    phone = models.CharField(max_length=120)
    address = models.TextField()
    email = models.EmailField(unique=True)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.full_name} : {self.email}"

    def get_absolute_url(self):

        return reverse('customers:customer-detail', kwargs={
            'pk': self.pk,
        })

customers/forms.py
from django import forms
from django.forms import fields
from .models import Customer


class CustomerForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['full_name'].widget.attrs.update(
            {'class': 'form-control', })
        self.fields['phone'].widget.attrs.update(
            {'class': 'form-control', })
        self.fields['address'].widget.attrs.update(
            {'class': 'form-control', })
        self.fields['email'].widget.attrs.update(
            {'class': 'form-control', })

    class Meta:

        model = Customer
        fields = '__all__'

customers/views.py
from orders.models import Order
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.http.response import HttpResponseRedirect
from django.shortcuts import render, redirect
from django.urls import reverse
from .models import Customer
from .forms import CustomerForm
from .filters import CustomerFilter
from accounts.decorators import allowed_users
from orders.filters import OrderFilter1, OrderFilter2


@login_required(login_url='accounts:login')
@allowed_users(allowed_roles=['admin'])
def customer_list(request):

    customers = Customer.objects.all()
    my_filter = CustomerFilter(request.GET, queryset=customers)
    customers = my_filter.qs

    return render(request, 'customers/customer_list.html', {

        'my_filter': my_filter,
        'customers': customers,
    })


@login_required(login_url='accounts:login')
@allowed_users(allowed_roles=['admin'])
def customer_detail(request, pk):

    customer = Customer.objects.get(pk=pk)
    related_orders = customer.order_set.all()
    total_orders = related_orders.count()

    my_filter = OrderFilter1(request.GET, queryset=related_orders)
    related_orders = my_filter.qs

    return render(request, 'customers/customer_detail.html', {
        'customer': customer,
        'related_orders': related_orders,
        'total_orders': total_orders,
        'my_filter': my_filter,
    })


@login_required(login_url='accounts:login')
@allowed_users(allowed_roles=['admin'])
def customer_create(request):

    form = CustomerForm()

    if request.method == 'POST':
        form = CustomerForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('core:dashboard')

    return render(request, 'customers/customer_create.html', {

        'form': form,

    })


@login_required(login_url='accounts:login')
@allowed_users(allowed_roles=['admin'])
def customer_update(request, pk):

    customer = Customer.objects.get(pk=pk)
    form = CustomerForm(instance=customer)

    if request.method == 'POST':
        form = CustomerForm(request.POST, instance=customer)

        if form.is_valid():
            form.save()
            messages.success(request, ('Customer updated.'))
            return HttpResponseRedirect(reverse('customers:customer-detail', args=[customer.pk]))

    return render(request, 'customers/customer_create.html', {

        'form': form,

    })


@login_required(login_url='accounts:login')
@allowed_users(allowed_roles=['admin'])
def customer_delete(request, pk):

    customer = Customer.objects.get(pk=pk)

    if request.method == 'POST':
        customer.delete()
        messages.success(request, ('Customer deleted.'))
        return redirect('customers:customer-list')

    return render(request, 'customers/customer_delete.html', {

        'customer': customer,

    })

customers/templates/customers/customer_create.html
{% extends 'base.html' %}
{% block title%} Create Customer {% endblock %}
{% block content %}
<div class="container mt-5 shadow p-3 mb-5 rounded">
    <h2 class="dsubhead fs-4 mt-3 mb-0 text-center pb-5">Customer:</h2>
    <form class="" action="" method="POST" class="">
        {% csrf_token %}
        {{ form.as_p }}
        <button class="form-control btn btn-info" type="submit" name="Submit">Submit</button>
    </form>
</div>
{% endblock content %}

customers/templates/customers/customer_delete.html
{% extends 'base.html' %}
{% block title %}Customer Delete{% endblock title %}
{% block content %}
<div class="container mt-5">
    <div class="row">
        <div class="col-md">
            <div class="card card-body shadow">
                <h5 class="text-center pt-2">Are you sure you want to delete: {{ customer }}?</h5>
            </div>
            <div class="card card-body shadow">
                <form action="" method="POST">
                    {% csrf_token %}
                    <a class="btn btn-info" href="{% url 'customers:customer-list' %}">Cancel</a>
                    <button class="btn btn-danger" type="submit" name="Submit">Delete</button>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

customers/templates/customers/customer_detail.html
{% extends 'base.html' %}
{% block title %}{{ customer.full_name }}{% endblock title %}
{% block content %}
{% load crispy_forms_tags %}
<div class="row mt-5">
    <div class="col-md">
        <div class="card card-body shadow">
            <h5>Customer:</h5>
            <p><strong>{{ customer.full_name }}</strong></p>
            <hr>
            <a class="btn btn-outline-primary  btn-sm btn-block mt-2"
                href="{% url 'orders:order-create-customer' customer.pk %}">Place Order</a>
            <a class="btn btn-info  btn-sm btn-block mt-2"
                href="{% url 'customers:customer-update' customer.pk %}">Update Customer</a>
            <a class="btn btn-danger  btn-sm btn-block mt-2"
                href="{% url 'customers:customer-delete' customer.pk %}">Delete Customer</a>
        </div>
    </div>
    <div class="col-md">
        <div class="card card-body shadow">
            <h5>Contact Information</h5>
            <hr>
            <p>Email: {{ customer.email }}</p>
            <p>Phone: {{ customer.phone }}</p>
            <p>Address: {{ customer.address }}</p>
        </div>
    </div>
    <div class="col-md">
        <div class="card card-body shadow">
            <h5>Total Orders</h5>
            <hr>
            <h1 style="text-align: center;padding: 10px">{{ total_orders }}</h1>
        </div>
    </div>
</div>
<br>
<div class="row">
    <div class="col">
        <div class="card card-body shadow">
            <form method="get">
                {{ my_filter.form|crispy }}
                <button class="btn btn-primary w-100 mt-3" type="submit">Search</button>
            </form>
        </div>
    </div>
</div>
<br>
<div class="row">
    <div class="col-md">
        <div class="card card-body shadow">
            <h5><strong>Orders :</strong></h5>
            <table class="table table-hover align-middle text-center">
                <thead>
                    <tr>
                        <th>Product</th>
                        <th>Created</th>
                        <th>Status</th>
                        <th>Update</th>
                        <th>Remove</th>
                    </tr>
                </thead>
                <tbody>
                    {% for order in related_orders %}
                    <tr>
                        <th class="my-main-text">{{ order.product.name }}</th>
                        <th class="my-main-text">{{ order.date_created}}</th>
                        {% if order.status == 'PENDING'%}
                        <th><span class="mystatus-pending"><strong>{{ order.status }}</strong></span></th>
                        {% elif order.status == 'READY' %}
                        <th><span class="mystatus-ready"><strong>{{ order.status }}</strong></span></th>
                        {% elif order.status == 'DELIVERED' %}
                        <th><span class="mystatus-delivered"><strong>{{ order.status }}</strong></span></th>
                        {% endif %}
                        <th><a class="btn btn-sm btn-info w-100"
                                href="{% url 'orders:order-update' order.pk %}">Update</a></th>
                        <th><a class="btn btn-sm btn-danger w-100"
                                href="{% url 'orders:order-delete' order.pk %}">Remove</a></th>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>
{% endblock %}

customers/templates/customers/customer_filter.html
{% load static %}
{% load crispy_forms_tags %}
<div class="container mt-5 ">
    <div class="row">
        <div class="col-md">
            <div class="card card-body shadow">
                <h5 class="text-center pt-2"><strong>Filter Customers</strong></h5>
            </div>
            <div class="col">
                <div class="card card-body shadow">
                    <form class="" method="GET" action="">
                        {{ my_filter.form | crispy }}
                        <button class="btn btn-info mt-3 w-100" type="submit">Search</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

customers/templates/customers/customer_list.html
{% extends 'base.html' %}
{% block title %}Customers{% endblock title %}
{% block content %}
{% include 'customers/customer_filter.html' %}
<div class="container mt-5">
    <div class="row">
        <div class="col-md">
            <div class="card card-body shadow">
                <h5 class="text-center pt-2"><strong>Customers</strong></h5>
            </div>
            <div class="card card-body shadow">
                <table class="table table-hover text-center align-middle">
                    <thead>
                        <tr>
                            <th>Full Name</th>
                            <th>Phone</th>
                            <th>Email</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for customer in customers %}
                        <tr>
                            <th><a href="{{ customer.get_absolute_url }}">{{ customer.full_name }}</a></th>
                            <th>{{ customer.phone }}</th>
                            <th>{{ customer.email }}</th>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
{% endblock content %}