accounts/urls.py
from django.urls import path
from .views import register_user, login_user, logout_user


app_name = 'accounts'


urlpatterns = [
    path('login/', login_user, name='login'),
    path('register/', register_user, name='register'),
    path('logout/', logout_user, name='logout'),
]

brands/urls.py
from django.urls import path
from .views import brand_list, brand_create, brand_detail, brand_update, brand_delete

app_name = 'brands'

urlpatterns = [
    path('', brand_list, name='brand-list'),
    path('<int:pk>/', brand_detail, name='brand-detail'),
    path('create/', brand_create, name='brand-create'),
    path('update/<int:pk>/', brand_update, name='brand-update'),
    path('delete/<int:pk>/', brand_delete, name='brand-delete'),
]

core/urls.py
from django.urls import path
from .views import dashboard, home_page

app_name = 'core'

urlpatterns = [
    path('', home_page, name='home'),
    path('dashboard/', dashboard, name='dashboard')
]

main/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('products/', include('products.urls', namespace='products')),
    path('customers/', include('customers.urls', namespace='customers')),
    path('brands/', include('brands.urls', namespace='brands')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('authentication/', include('accounts.urls', namespace='accounts')),
]


# Adding STATIC and MEDIA
urlpatterns += static(settings.STATIC_URL,
                      document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL,
                      document_root=settings.MEDIA_ROOT)


admin.site.site_header = "shisaStore"

orders/urls.py
from django.urls import path
from .views import order_create, order_create_customer, order_detail, order_list, order_update, order_delete, order_create_customer

app_name = 'orders'

urlpatterns = [
    path('', order_list, name='order-list'),
    path('<int:pk>/', order_detail, name='order-detail'),

    path('create/', order_create, name='order-create'),
    path('create/<int:pk>', order_create_customer, name='order-create-customer'),
    path('update/<int:pk>', order_update, name='order-update'),
    path('delete/<int:pk>', order_delete, name='order-delete'),

]

products/urls.py
from django.urls import path
from .views import product_list, product_detail, product_create, product_update, product_delete


app_name = 'products'

urlpatterns = [
    path('', product_list, name='product-list'),
    path('<int:pk>/', product_detail, name='product-detail'),
    path('create/', product_create, name='product-create'),
    path('update/<int:pk>/', product_update, name='product-update'),
    path('delete/<int:pk>/', product_delete, name='product-delete'),
]

templates/base.html
{% load static %}
<!Doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We" crossorigin="anonymous">

    <title>shisaShop | {% block title %}{% endblock title %}</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Titillium+Web:wght@300;400;700&display=swap" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
</head>

<body>
    {% include 'navbar.html' %}
    {% if messages %}
    {% for message in messages %}
    <div class="container">
        <div class="alert alert-info alert-dismissible fade show mt-5" role="alert">
            {{ message }}
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
    </div>
    {% endfor %}
    {% endif %}
    {% block content %}
    {% endblock content %}
    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-U1DAWAznBHeqEIlVSCgzq+c9gqGAJn5c/t99JyeKa9xxaYpSvHU5awsuZVVFIhvj"
        crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.3/dist/umd/popper.min.js" integrity="sha384-eMNCOe7tC1doHpGoWe/6oMVemdAVTMs2xqW4mwXrXsW0L84Iytr2wi5v2QjrP/xp" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.min.js" integrity="sha384-cn7l7gDp0eyniUwwAZgrzD06kc/tftFf19TOAs2zVinnD/C7E91j9yyk5//jjpt/" crossorigin="anonymous"></script>
    -->
</body>

</html>

templates/navbar.html
{% load static %}
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
        <a class="navbar-brand" href="/">Shisa</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown"
            aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">

            <ul class="navbar-nav">
                {% if request.user.is_authenticated %}
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button"
                        data-bs-toggle="dropdown" aria-expanded="false">
                        Dashboard
                    </a>
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                        <li><a class="dropdown-item" href="{% url 'core:dashboard' %}">Dashboard</a></li>
                        <li><a class="dropdown-item" href="#">Another action</a></li>
                        <li><a class="dropdown-item" href="#">Something else here</a></li>
                    </ul>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button"
                        data-bs-toggle="dropdown" aria-expanded="false">
                        Orders
                    </a>
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                        <li><a class="dropdown-item" href="{% url 'orders:order-list' %}">Orders</a></li>
                        <li><a class="dropdown-item" href="{% url 'orders:order-create' %}">Add Order</a></li>
                        <li><a class="dropdown-item" href="#">Something else here</a></li>
                    </ul>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button"
                        data-bs-toggle="dropdown" aria-expanded="false">
                        Products
                    </a>
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                        <li><a class="dropdown-item" href="{% url 'products:product-list' %}">Products</a></li>
                        <li><a class="dropdown-item" href="{% url 'products:product-create' %}">Add Product</a></li>
                        <li><a class="dropdown-item" href="#">Something else here</a></li>
                    </ul>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button"
                        data-bs-toggle="dropdown" aria-expanded="false">
                        Customers
                    </a>
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                        <li><a class="dropdown-item" href="{% url 'customers:customer-list' %}">Customers</a></li>
                        <li><a class="dropdown-item" href="{% url 'customers:customer-create' %}">Add Customer</a></li>
                        <li><a class="dropdown-item" href="#">Something else here</a></li>
                    </ul>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button"
                        data-bs-toggle="dropdown" aria-expanded="false">
                        Brands
                    </a>
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                        <li><a class="dropdown-item" href="{% url 'brands:brand-list' %}">Brands</a></li>
                        <li><a class="dropdown-item" href="{% url 'brands:brand-create' %}">Add Brand</a></li>
                        <li><a class="dropdown-item" href="#">Something else here</a></li>
                    </ul>
                </li>
                {% else %}
                {% endif %}
                {% if request.user.is_authenticated %}
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button"
                        data-bs-toggle="dropdown" aria-expanded="false">
                        {{ request.user.username }}
                    </a>
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                        <li><a class="dropdown-item" href="{% url 'accounts:logout' %}">Logout</a></li>
                        <li><a class="dropdown-item" href="#">Profile of: {{ request.user.username }}</a></li>
                        <li><a class="dropdown-item" href="#">Something else here</a></li>
                    </ul>
                </li>
                {% else %}
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button"
                        data-bs-toggle="dropdown" aria-expanded="false">
                        Authenticate
                    </a>
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                        <li><a class="dropdown-item" href="{% url 'accounts:login' %}">Login</a></li>
                        <li><a class="dropdown-item" href="{% url 'accounts:register' %}">Register</a></li>
                        <li><a class="dropdown-item" href="#">Something else here</a></li>
                    </ul>
                </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>

templates/status.html
<div class="row mt-5">
    <div class="col">
        <div class="cold-md">
            <div class="card text-center text-white mb-3 shadow" id="total-orders">
                <div class="card-header">
                    <h5 class="card-title">Total Orders</h5>
                </div>
                <div class="card-body">
                    <h3 class="card-title">{{ total_orders }}</h3>
                </div>
            </div>
        </div>
    </div>

    <div class="col">
        <div class="col-md">
            <div class="card text-center text-white mb-3 shadow" id="orders-delivered">
                <div class="card-header">
                    <h5 class="card-title">Orders Delivered</h5>
                </div>
                <div class="card-body">
                    <h3 class="card-tittle">{{ delivered }}</h3>
                </div>
            </div>
        </div>
    </div>

    <div class="col">
        <div class="col-md">
            <div class="card text-center text-white mb-3 shadow" id="orders-pending">
                <div class="card-header">
                    <h5 class="card-title">Orders Pending</h5>
                </div>
                <div class="card-body">
                    <h3 class="card-title">{{ pending }}</h3>
                </div>
            </div>
        </div>
    </div>
</div>