core/urls.py
from django.urls import path
from .views import dashboard, home_page

app_name = 'core'

urlpatterns = [
    path('', home_page, name='home'),
    path('dashboard/', dashboard, name='dashboard')
]

main/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('products/', include('products.urls', namespace='products')),
    path('customers/', include('customers.urls', namespace='customers')),
    path('brands/', include('brands.urls', namespace='brands')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('authentication/', include('accounts.urls', namespace='accounts')),
]


# Adding STATIC and MEDIA
urlpatterns += static(settings.STATIC_URL,
                      document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL,
                      document_root=settings.MEDIA_ROOT)


admin.site.site_header = "shisaStore"

products/urls.py
from django.urls import path
from .views import product_list, product_detail, product_create, product_update, product_delete


app_name = 'products'

urlpatterns = [
    path('', product_list, name='product-list'),
    path('<int:pk>/', product_detail, name='product-detail'),
    path('create/', product_create, name='product-create'),
    path('update/<int:pk>/', product_update, name='product-update'),
    path('delete/<int:pk>/', product_delete, name='product-delete'),
]

products/models.py
from django.db import models
from django.urls import reverse
from brands.models import Brand
from tags.models import Tag


class Product(models.Model):

    CATEGORY = (
        ('Karate', 'Karate'),
        ('Judo', 'Judo'),
        ('Aikido', 'Aikido'),
        ('Boxing', 'Boxing'),
        ('Muai Tai', 'Muai Tai'),
        ('Training', 'Training'),
        ('Outdoor', 'Outdoor'),
        ('Shoes', 'Shoes'),
    )

    name = models.CharField(max_length=120)
    price = models.DecimalField(max_digits=20, decimal_places=2)
    brand = models.ForeignKey(
        Brand, on_delete=models.SET_NULL, null=True, blank=True)
    category = models.CharField(max_length=120, choices=CATEGORY)
    description = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    tag = models.ManyToManyField(Tag)

    def __str__(self):
        return f"{self.id}: {self.name} - {self.price}"

    def get_absolute_url(self):

        return reverse('products:product-detail', kwargs={
            'pk': self.pk,
        })

products/forms.py
from django import forms
from .models import Product


class ProductForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['name'].widget.attrs.update({'class': 'form-control'})
        self.fields['price'].widget.attrs.update({'class': 'form-control'})
        self.fields['brand'].widget.attrs.update({'class': 'form-control'})
        self.fields['category'].widget.attrs.update({'class': 'form-control'})
        self.fields['description'].widget.attrs.update(
            {'class': 'form-control'})
        self.fields['tag'].widget.attrs.update(
            {'class': 'form-control'})

    price = forms.DecimalField(
        required=False, max_digits=6, decimal_places=2, min_value=0)

    class Meta:

        model = Product
        fields = '__all__'

        widgets = {
            'price': forms.NumberInput(attrs={}),
        }

products/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import HttpResponseRedirect, render, redirect
from django.contrib import messages
from django.urls import reverse
from .models import Product
from .forms import ProductForm
from .filters import ProductFilter
from accounts.decorators import allowed_users
from orders.filters import OrderFilter1, OrderFilter2


# All Products.
@login_required(login_url='accounts:login')
@allowed_users(allowed_roles=['admin'])
def product_list(request):

    products = Product.objects.all()
    my_filter = ProductFilter(request.GET, queryset=products)
    products = my_filter.qs

    context = {
        'my_filter': my_filter,
        'products': products,
    }

    return render(request, 'products/product_list.html', context)


@login_required(login_url='accounts:login')
@allowed_users(allowed_roles=['admin'])
def product_detail(request, pk):

    product = Product.objects.get(pk=pk)
    related_orders = product.order_set.all()
    total_orders = related_orders.count() / 100

    my_filter = OrderFilter2(request.GET, queryset=related_orders)
    related_orders = my_filter.qs

    return render(request, 'products/product_detail.html', {

        'product': product,
        'related_orders': related_orders,
        'total_orders': total_orders,
        'my_filter': my_filter,

    })


@login_required(login_url='accounts:login')
@allowed_users(allowed_roles=['admin'])
def product_create(request):

    form = ProductForm()

    if request.method == 'POST':
        form = ProductForm(request.POST)

        if form.is_valid():
            form.save()
            messages.success(request, ('Product created.'))
            return redirect('products:product-list')

    return render(request, 'products/product_create.html', {

        'form': form,

    })


@login_required(login_url='accounts:login')
@allowed_users(allowed_roles=['admin'])
def product_update(request, pk):

    product = Product.objects.get(pk=pk)
    form = ProductForm(instance=product)

    if request.method == 'POST':
        form = ProductForm(request.POST, instance=product)

        if form.is_valid():
            form.save()
            messages.success(request, ('Product updated.'))
            return HttpResponseRedirect(reverse('products:product-detail', args=[product.pk]))

    return render(request, 'products/product_create.html', {

        'form': form,

    })


@login_required(login_url='accounts:login')
@allowed_users(allowed_roles=['admin'])
def product_delete(request, pk):

    product = Product.objects.get(pk=pk)

    if request.method == 'POST':
        product.delete()
        messages.success(request, ('Product deleted.'))
        return redirect('products:product-list')

    return render(request, 'products/product_delete.html', {

        'product': product,

    })

products/templates/products/product_create.html
{% extends 'base.html' %}
{% block title%} Add Product {% endblock %}
{% block content %}
<div class="container mt-5 shadow p-3 mb-5 rounded">
    <h2 class="dsubhead fs-4 mt-3 mb-0 text-center pb-5">Product:</h2>
    <form class="" action="" method="POST" class="">
        {% csrf_token %}
        {{ form }}
        <button class="form-control btn btn-info" type="submit" name="Submit">Submit</button>
    </form>
</div>
{% endblock content %}

products/templates/products/product_delete.html
{% extends 'base.html' %}
{% block title %}Product Delete{% endblock title %}
{% block content %}
<div class="container mt-5">
    <div class="row">
        <div class="col-md">
            <div class="card card-body shadow">
                <h5 class="text-center pt-2">Are you sure you want to delete: {{ product }}?</h5>
            </div>
            <div class="card card-body shadow">
                <form action="" method="POST">
                    {% csrf_token %}
                    <a class="btn btn-info" href="{% url 'products:product-list' %}">Cancel</a>
                    <button class="btn btn-danger" type="submit" name="Submit">Delete</button>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

products/templates/products/product_detail.html
{% extends 'base.html' %}
{% block title %}{{ product.name }}{% endblock title %}
{% block content %}
{% load crispy_forms_tags %}
<div class="row mt-5">
    <div class="col-md">
        <div class="card card-body shadow">
            <h5>Product:</h5>
            <p><strong>{{ product.name }}</strong></p>
            <hr>
            <a class="btn btn-info  btn-sm btn-block mt-2" href="{% url 'products:product-update' product.pk %}">Update
                Product</a>
            <a class="btn btn-danger  btn-sm btn-block mt-2"
                href="{% url 'products:product-delete' product.pk %}">Delete Product</a>

        </div>
    </div>
    <div class="col-md">
        <div class="card card-body shadow">
            <h5>Product Information:</h5>
            <hr>
            <p>Price: <strong>{{ product.price }}</strong></p>
            <p>Producer: <strong>{{ product.brand.name }}</strong></p>
            <p>Category: <strong>{{ product.category }}</strong></p>
            <p>Tag:{% for tag in product.tag.all %} <strong>{{ tag }}</strong>, {% endfor %}</p>
        </div>
    </div>
    <div class="col-md">
        <div class="card card-body shadow">
            <h5>Rotation:</h5>
            <hr>
            <h1 style="text-align: center;padding: 10px">{{ total_orders }}</h1>
        </div>
    </div>
</div>
<br>
<div class="row">
    <div class="col">
        <div class="card card-body shadow">
            <form method="get">
                {{ my_filter.form | crispy }}
                <button class="btn btn-primary w-100 mt-3" type="submit">Search</button>
            </form>
        </div>
    </div>
</div>
<br>
<div class="row">
    <div class="col-md">
        <div class="card card-body shadow">
            <h5>Orders:</h5>
            <table class="table table-hover text-center align-middle">
                <thead>
                    <tr>
                        <th>Order ID:</th>
                        <th>Customer Name</th>
                        <th>Date Orderd</th>
                        <th>Status</th>
                        <th>Update</th>
                        <th>Remove</th>
                    </tr>
                </thead>
                <tbody>
                    {% for order in related_orders %}
                    <tr>
                        <th class="">{{ order.id }}</th>
                        <th class="my-main-text">{{ order.customer.full_name }}</th>
                        <th class="my-main-text">{{ order.date_created }}</th>
                        {% if order.status == 'PENDING'%}
                        <th><span class="mystatus-pending"><strong>{{ order.status }}</strong></span></th>
                        {% elif order.status == 'READY' %}
                        <th><span class="mystatus-ready"><strong>{{ order.status }}</strong></span></th>
                        {% elif order.status == 'DELIVERED' %}
                        <th><span class="mystatus-delivered"><strong>{{ order.status }}</strong></span></th>
                        {% endif %}
                        <th><a class="btn btn-sm btn-info m-2 w-100" href="#">Update</a></th>
                        <th><a class="btn btn-sm btn-danger m-2 w-100" href="#">Remove</a></th>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>

{% endblock %}

products/templates/products/product_filter.html
{% load static %}
{% load crispy_forms_tags %}
<div class="container mt-5">
    <div class="row">
        <div class="col-md">
            <div class="card card-body shadow">
                <h5 class="text-center pt-2">Filter Products</h5>
            </div>
            <div class="col">
                <div class="card card-body">
                    <form method="GET" action="">
                        {{ my_filter.form | crispy }}
                        <button class="btn btn-info mt-3 w-100" type="submit">Search</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

products/templates/products/product_list.html
{% extends 'base.html' %}
{% block title %}Products{% endblock title %}
{% block content %}
{% include 'products/product_filter.html' %}
<div class="container mt-5">
    <div class="row">
        <div class="col-md">
            <div class="card card-body shadow">
                <h5 class="text-center pt-2">Products</h5>
            </div>
            <div class="card card-body shadow">
                <table class="table text-center">
                    <tr>
                        <th>Product</th>
                        <th>Category</th>
                        <th>Price</th>
                        <th>Brand</th>
                    </tr>
                    {% for product in products %}
                    <tr>
                        <th><a href="{{ product.get_absolute_url }}">{{ product.name }}</a></th>
                        <th>{{ product.category}}</th>
                        <th>{{ product.price }}</th>
                        <th>{{ product.brand }}</th>
                    </tr>
                    {% endfor %}
                </table>
            </div>
        </div>
    </div>
</div>
{% endblock content %}